version: '3' # docker version
services:
  www:
    build: . # Use the current directory for the Dockerfile
    volumes:
      - "./:/var/www/html" # sync project dir with container web dir
    ports:
      - "8081:80"